assets:
  host.path: ${user.home}/.config/home-ops/host.json
  hosts.path: ${user.home}/.ansible/inventory/hosts.toml
spring:
  toml:
    enabled: true
  shell:
    theme:
      name: "monokai-filter-spectrum"
    interactive:
      enabled: true
    command:
      stacktrace:
        enabled: false
      script:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  config:
    import:
      - "file://${assets.host.path}"
      - "file://${user.home}/.config/home-ops/default.toml"
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: lazy
    redis:
      host: http://192.168.2.202
      port: 6379

  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.home}/.local/share/automation/home-db/home-ops.sqlite
    username: ""
    password: ""
  task:
    scheduling:
      pool.size: 5
      shutdown:
        await-termination: true
        await-termination-period: 30s

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
logging:
  level:
    root: WARN
#db:
#  property-sources:
#    - table: "hosts"
#  property-refresh-interval: 5s

database:
  persistence:
    check:
      interval: 300000 # 5 minutes in milliseconds

